
export enum TypeInstitutionEnum {
    INSTITUTION_HOPI = 'INSTITUTION_HOPI',
    INSTITUTION_PHARMA = 'INSTITUTION_PHARMA',
    INSTITUTION_ASSURANCE = 'INSTITUTION_ASSURANCE',
    INSTITUTION_COMMUNE = 'INSTITUTION_COMMUNE'
}